<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-05-02 05:46
=======
# Generated by Django 6.0.4 on 2026-05-01 04:18
>>>>>>> e9f6aeeac7a6ec25f7db247fd35f354f53b26526

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
<<<<<<< HEAD
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_status', models.CharField(choices=[('LOST', 'Lost Item'), ('FOUND', 'Found Item')], default='LOST', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('documents', 'Documents'), ('personal', 'Personal'), ('others', 'Others')], max_length=50, null=True)),
                ('sub_category', models.CharField(blank=True, choices=[('electronics', [('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('earphones', 'Earphones'), ('charger', 'Charger'), ('other', 'Other')]), ('documents', [('student ID', 'Student ID'), ('national ID', 'National ID'), ('passport', 'Passport'), ('ATM Card', 'ATM Card'), ('Other', 'Other')]), ('personal', [('wallet', 'Wallet'), ('keys', 'Keys'), ('backpack', 'Backpack'), ('watch', 'Watch'), ('other', 'Other')]), ('others', [('water bottle', 'Water Bottle'), ('umbrella', 'Umbrella'), ('books', 'Books'), ('tools', 'Tools'), ('other', 'Other')])], max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('silver/grey', 'Silver/Grey'), ('blue', 'Blue'), ('red', 'Red'), ('gold', 'Gold'), ('other', 'Other')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('exact_location', models.CharField(blank=True, max_length=150, null=True)),
                ('additional_location', models.CharField(blank=True, max_length=150, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_status', models.CharField(choices=[('LOST', 'Lost Item'), ('FOUND', 'Found Item')], default='LOST', max_length=20)),
                ('item_type', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('documents', 'Documents'), ('personal', 'Personal'), ('others', 'Others')], max_length=50, null=True)),
                ('sub_category', models.CharField(blank=True, choices=[('electronics', [('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('earphones', 'Earphones'), ('charger', 'Charger'), ('other', 'Other')]), ('documents', [('student ID', 'Student ID'), ('national ID', 'National ID'), ('passport', 'Passport'), ('ATM Card', 'ATM Card'), ('Other', 'Other')]), ('personal', [('wallet', 'Wallet'), ('keys', 'Keys'), ('backpack', 'Backpack'), ('watch', 'Watch'), ('other', 'Other')]), ('others', [('water bottle', 'Water Bottle'), ('umbrella', 'Umbrella'), ('books', 'Books'), ('tools', 'Tools'), ('other', 'Other')])], max_length=50, null=True)),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('Silver/Grey', 'Silver/Grey'), ('blue', 'Blue'), ('red', 'Red'), ('Gold', 'Gold'), ('other', 'Other')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('exact_location', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_location', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
>>>>>>> e9f6aeeac7a6ec25f7db247fd35f354f53b26526
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Home.item')),
            ],
        ),
    ]
