# Generated by Django 6.0.4 on 2026-05-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('LOST', 'Lost Item'), ('FOUND', 'Found Item'), ('CLAIMED', 'Claimed Item')], default='LOST', max_length=20),
        ),
    ]
